MvcCubos/Models/BlobModel.cs
namespace MvcCubos.Models
{
    public class BlobModel
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Contenedor { get; set; }
    }

}

MvcCubos/Models/Cubo.cs
namespace MvcCubos.Models
{
    public class Cubo
    {
        public int Id { get; set; }

        public string Nombre { get; set; }

        public string Marca { get; set; }

        public string Imagen { get; set; }

        public int Precio { get; set; }

    }
}

MvcCubos/Models/ErrorViewModel.cs
namespace MvcCubos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCubos/Models/LoginModel.cs
namespace MvcCubos.Models
{
    public class LoginModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

MvcCubos/Models/Pedido.cs
namespace MvcCubos.Models
{
    public class Pedido
    {

        public int IdPedido { get; set; }

        public int IdCubo { get; set; }

        public int IdUsuario { get; set; }

        public DateTime Fecha { get; set; }
    }
}

MvcCubos/Models/Usuario.cs
namespace MvcCubos.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Imagen { get; set; }
    }
}

MvcCubos/Controllers/CubosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCubos.Models;
using MvcCubos.Services;

namespace MvcCubos.Controllers
{
    public class CubosController : Controller
    {

        private ServiceApiCubos service;
        private ServiceStorageBlobs storageBlob;

        public CubosController(ServiceApiCubos service, ServiceStorageBlobs storageBlob)
        {
            this.service = service;
            this.storageBlob = storageBlob;
        }

        public async Task<IActionResult> Index()
        {
            List<Cubo> cubos = await this.service.GetCubos();

            foreach (Cubo cubo in cubos)
            {
                cubo.Imagen = await this.storageBlob.GetUrl("cubospublic", cubo.Imagen);
            }

            return View(cubos);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string marca)
        {
            List<Cubo> cubos = await this.service.GetCubosMarca(marca);

            foreach (Cubo cubo in cubos)
            {
                cubo.Imagen = await this.storageBlob.GetUrl("cubospublic", cubo.Imagen);
            }

            return View(cubos);
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string nombre, string marca, IFormFile imagen, int precio)
        {

            string blobName = imagen.FileName;
            using (Stream stream = imagen.OpenReadStream())
            {
                await this.storageBlob.UploadBlobAsync("cubospublic", blobName, stream);
            }

            await this.service.CreateCubo(nombre, marca, blobName, precio);



            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Comprar(int id)
        {
            await this.service.ComprarCubo(id, HttpContext.Session.GetString("TOKEN"));
            return RedirectToAction("Index");
        }
    }
}

MvcCubos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCubos.Models;
using System.Diagnostics;

namespace MvcCubos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCubos/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using MvcCubos.Services;

namespace MvcCubos.Controllers
{
    public class ManagedController : Controller
    {

        private ServiceApiCubos service;
        private ServiceStorageBlobs serviceStorageBlobs;

        public ManagedController(ServiceApiCubos service, ServiceStorageBlobs serviceStorageBlobs)
        {
            this.service = service;
            this.serviceStorageBlobs = serviceStorageBlobs;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            string token = await this.service.GetTokenAsync(email, password);
            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
            else
            {
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                Claim claimUserName = new Claim(ClaimTypes.Name, email);
                Claim claimRole = new Claim(ClaimTypes.Role, "USUARIO");
                identity.AddClaim(claimUserName);
                identity.AddClaim(claimRole);
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                //INTRODUCIMOS AL USUARIO EN EL SISTEMA
                await HttpContext.SignInAsync
                    (
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal,
                    new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.Now.AddMinutes(15)
                    });
                return RedirectToAction("Index", "Cubos");

            }
        }


        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Cubos");
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(string nombre, string email, IFormFile file, string password)
        {
            string blobName = file.FileName;
            using (Stream stream = file.OpenReadStream())
            {
                await this.serviceStorageBlobs.UploadBlobAsync("cubosprivate", blobName, stream);
            }

            await this.service.RegisterUser(nombre, email, blobName, password);
            return RedirectToAction("Login");
        }
    }
}

MvcCubos/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCubos.Models;
using MvcCubos.Services;

namespace MvcCubos.Controllers
{
    public class UsuariosController : Controller
    {

        private ServiceApiCubos service;
        private ServiceStorageBlobs storageBlob;

        public UsuariosController(ServiceApiCubos service, ServiceStorageBlobs storageBlob)
        {
            this.service = service;
            this.storageBlob = storageBlob;
        }

        public async Task<IActionResult> Perfil()
        { 
            Usuario usuario = await this.service.GetPerfil(HttpContext.Session.GetString("TOKEN"));
            usuario.Imagen = await this.storageBlob.GetUrl("cubosprivate", usuario.Imagen);

            List<Pedido> pedidos = await this.service.GetPedidos(HttpContext.Session.GetString("TOKEN"));
            ViewData["PEDIDOS"] = pedidos;
            return View(usuario);
        }
    }
}

MvcCubos/Views/Cubos/Create.cshtml
@model MvcCubos.Models.Cubo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cubo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input type="text" name="nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input type="text" name="marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">s
                <label class="control-label"></label>
                <input type="file" name="imagen" class="form-control" />
                @*<span asp-validation-for="Imagen" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input type="number" name="precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCubos/Views/Cubos/Index.cshtml
@model List<Cubo>

@{
    ViewData["Title"] = "Index";
}


<h3>BUSCADOR POR MARCA:</h3>
<form method="post">
    <label>Marca:</label>
    <input class="form-control" type="text" name="marca" />
    <button class="btn btn-primary">BUSCAR</button>
</form>

<a asp-action="Create" asp-controller="Cubos">Crear nuevo cubo</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Marca
            </th>
            <th>
                Imagen
            </th>
            <th>
                Precio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    <img src="@item.Imagen" width="100px" height="100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                @if (Context.User.Identity.Name != null)
                {
                    <td>
                        <a class="btn btn-primary" asp-action="Comprar" asp-controller="Cubos" asp-route-id="@item.Id">
                            Comprar
                        </a>

                    </td>
                }
            </tr>
        }
    </tbody>
</table>

MvcCubos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCubos/Views/Managed/Login.cshtml
<h1 style="color:blue">
    Log In Usuario
</h1>

<form method="post">
    <label>Email:</label>
    <input type="text" name="email" class="form-control" required />
    <label>Password:</label>
    <input type="text" name="password" class="form-control" required />
    <button class="btn btn-info">
        Log In
    </button>
</form>

<h2 style="color:red">
    @ViewData["MENSAJE"]
</h2>

MvcCubos/Views/Managed/Register.cshtml
<h1 style="color:blue">
    Registro
</h1>

<form method="post" enctype="multipart/form-data">
    <label>Nombre:</label>
    <input type="text" name="nombre" class="form-control" required />
    <label>Imagen:</label>
    <input type="file" name="file" class="form-control" required />
    <label>Email:</label>
    <input type="text" name="email" class="form-control" required />
    <label>Password:</label>
    <input type="text" name="password" class="form-control" required />
    <button class="btn btn-info">
        Log In
    </button>
</form>

<h2 style="color:red">
    @ViewData["MENSAJE"]
</h2>

MvcCubos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCubos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCubos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCubos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cubos" asp-action="Index">Cubos</a>
                        </li>
                        @if (Context.User.Identity.Name == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Login" style="color:blue">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Register">Registro</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Perfil">Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Logout" style="color:red">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCubos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcCubos/Views/Usuarios/Perfil.cshtml
@model Usuario

<h1>USUARIO</h1>

<h2>Nombre: @Model.Nombre</h2>
<img src="@Model.Imagen" width="200px" height="200px" />
<h2>Email: @Model.Email</h2>

<h1>PEDIDOS</h1>
<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>FECHA</td>
            <td>ID_CUBO</td>
        </tr>
    </thead>
    <tbody>
        @foreach (Pedido p in (List<Pedido>)ViewData["PEDIDOS"])
        {
            <tr>
                <td>@p.IdPedido</td>
                <td>@p.Fecha</td>
                <td>@p.IdCubo</td>
            </tr>
        }
    </tbody>
</table>